<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXvS6qpr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXvS6qpr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXvS6qpr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXvS6qpr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXvS6qpr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XvS6qpr',
    'container.build_id' => '45c3d870',
    'container.build_time' => 1552445103,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXvS6qpr');
