<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSjzmXWL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSjzmXWL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSjzmXWL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSjzmXWL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSjzmXWL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SjzmXWL',
    'container.build_id' => '770eccf0',
    'container.build_time' => 1552925319,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSjzmXWL');
