<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1Zh3TFj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1Zh3TFj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1Zh3TFj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1Zh3TFj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1Zh3TFj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1Zh3TFj',
    'container.build_id' => 'a87999ce',
    'container.build_time' => 1552409689,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1Zh3TFj');
